{% set version = "1.18.0" %}

package:
  name: skopeo
  version: {{ version }}

source:
  url: https://github.com/containers/skopeo/archive/v{{ version }}.tar.gz
  sha256: 8a711db2bba3a357bebbbaf607ec731df6ea24c2d3cd9e0fef5e8fe9cefb154b
  folder: src
  patches:
    # NOTE: This adds the memfd_create syscall which is not available on CentOS 6's kernels.
    - 0001-Add-missing-defines-for-CentOS-6.patch
    - 0002-Allow-relative-paths-for-system-config-files.patch

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cgo') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - go-licenses
    - go-md2man
    - make
  host:
    - btrfs-progs  # [linux]
    - containers-common
    - gpgme  # [linux]
    - libassuan  # [linux]
    - libdevmapper  # [linux]
  run:
    - containers-common

test:
  commands:
    - skopeo --help
    - skopeo --version

about:
  home: https://github.com/containers/skopeo
  dev_url: https://github.com/containers/skopeo
  doc_url: https://github.com/containers/skopeo
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE
    - 3rd_party_licenses/
  summary: Perform operations on container images without docker daemon.
  description: |
    Skopeo can copy, inspect delete, sign and verify container images
    without requiring access to a docker daemon. It supports the local
    image store, API v2 registries, image archive (as created by
    docker save), OCI and OSTree and a local directory format.

extra:
  recipe-maintainers:
    - epruesse
    - bgruening
    - mbargull
    - dhirschfeld
