schema_version: 1

context:
  version: 1.15.2

package:
  name: skopeo
  version: ${{ version }}

source:
  url: https://github.com/containers/skopeo/archive/v${{ version }}.tar.gz
  sha256: 9d5e2163fe3bc0fc5d36d0e0e43e6e3cf26e12a855ae53e2aa4ddbe60acced3c
  target_directory: src

build:
  number: 0

requirements:
  build:
    - ${{ compiler("go-nocgo") }}
    - make
    - go-licenses
    - go-md2man
  run:
    - containers-common

tests:
  - script:
      - skopeo --help
      - skopeo --version

about:
  license: Apache-2.0
  license_file:
    - src/LICENSE
    - library_licenses/
  summary: Perform operations on container images without docker daemon.
  description: |
    Skopeo can copy, inspect delete, sign and verify container images
    without requiring access to a docker daemon. It supports the local
    image store, API v2 registries, image archive (as created by
    docker save), OCI and OSTree and a local directory format.
  homepage: https://github.com/containers/skopeo
  repository: https://github.com/containers/skopeo
  documentation: https://github.com/containers/skopeo

extra:
  recipe-maintainers:
    - epruesse
    - bgruening
    - mbargull
    - dhirschfeld
