schema_version: 1

context:
  version: 1.21.0

package:
  name: skopeo
  version: ${{ version }}

source:
  url: https://github.com/containers/skopeo/archive/v${{ version }}.tar.gz
  sha256: f76eeddf697a3cc7a872e3077ab4d0fdbebe9f3c6171462e3e9feb84368b3fac
  target_directory: src

build:
  number: 0
  skip:
    - win
  script:
    - cd src
    - make -C . install \
        DISABLE_CGO="1" \
        CONTAINERSCONFDIR="${PREFIX}/share/containers" \
        LOOKASIDEDIR="${PREFIX}/etc/containers/sigstore" \
        GIT_COMMIT=
    - rm -rf vendor/github.com/proglottis/gpgme
    - rm -f vendor/go.podman.io/image/v5/signature/mechanism_gpgme.go
    - rm -f vendor/go.podman.io/image/v5/signature/mechanism_gpgme_only.go
    - go-licenses save ./cmd/skopeo --save_path="../library_licenses"

requirements:
  build:
    - ${{ compiler("go-nocgo") }}
    - make
    - go-licenses
    - go-md2man
  run:
    - containers-common

tests:
  - script:
      - skopeo --help
      - skopeo --version
      - skopeo inspect --override-arch amd64 --override-os linux docker://docker.io/alpine

about:
  license: Apache-2.0
  license_file:
    - src/LICENSE
    - library_licenses/
  summary: Work with remote images registries - retrieving information, images, signing content
  homepage: https://github.com/containers/skopeo
  repository: https://github.com/containers/skopeo
  documentation: https://github.com/containers/skopeo

extra:
  recipe-maintainers:
    - epruesse
    - bgruening
    - mbargull
    - dhirschfeld
    - janjagusch
